[workspace]
members = ["bevy_spacetimedb", "macros"]

[workspace.dependencies]
bevy = { version = "0.17.3", default-features = false, features = [
    "std",
    "bevy_log",
] }
spacetimedb-sdk = { version = "1.11.1" }
