listen_addr = "0.0.0.0:3000"
jwt_pub_key_path = "/home/mortoc/Projects/bevy_spacetimedb_wasm/bevy_spacetimedb/js/.spacetime-dev/jwt-pub.key"
jwt_priv_key_path = "/home/mortoc/Projects/bevy_spacetimedb_wasm/bevy_spacetimedb/js/.spacetime-dev/jwt-priv.key"
